version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.4
jobs:
  test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: npm install
      - run: npm test
  deploy:
    docker:
      - image: circleci/node
    environment:
      AWS_REGION: eu-west-2
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - aws-s3/sync:
          from: build
          to: "s3://liam-richens-portfolio/"
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400" \
          overwrite: true
workflows:
  version: 2.1
  build:
    - deploy:
        filters:
          branches:
            only: master
