jobs:
  build_deploy:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Installing AWS CLI
          command: sudo apt-get update
            sudo apt install python3-pip
            sudo pip3 install awsebcli --upgrade
      - run: cd ./client && npm install && npm run build
      - run: aws s3 sync ./client/build s3://liam-richens-portfolio
  workflows:
    version: 2
    execute_bulk:
      jobs:
        - build-deploy
